### ISSUE TITLE
build_ar_environment issue

### ISSUE THREAD

**Issue by adriaan** [simplegeo/SGAREnvironment#1]
Hi, 

I'm trying to get SGAREnvironment up and running but am falling at the first hurdle. When I try and run build_ar_environment I get the following error:

---

Mac-mini:~ adriaan$ /Users/adriaan/simplegeo-SGAREnvironment-d7af2eb/build_ar_environment ; exit;
find: ./Classes: No such file or directory
Build settings from command line:
    PLATFORM_NAME = iphoneos
    SDKROOT = /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.1.sdk

xcodebuild: Error: the directory /Users/adriaan does not contain an Xcode project.
ERROR!
logout

---

Is there something (obvious) I'm missing here? I just downloaded the source and ran the build_ar_environment file. Anything else I need to be doing first?

Adriaan

**Comment by dsmith** [comment]
Hi Adriaan,

Sorry for the troubles. The _build_ar_environment_ script is intended to be executed from the _SGAREnvironment_ directory. The build script is not required to be executed in order to build the proper static libraries. You can use XCode to build the proper targets and builds.

Hope this helps.

Derek
